### ISSUE TITLE
Lab 01 - DimCustomer error

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/dp-203-azure-data-engineer#1]
# Module: 01
#### Step: 00

Description of issue
During setup:
![image](https://user-images.githubusercontent.com/10166617/214869600-49957db3-c651-4fdc-869f-363558b45ee0.png)

Repro steps:

1.
1.
1.

**Comment by GraemeMalcolm** [comment]
Non-repro for me - can you reclone the repo and try again?

**Comment by weslbo** [comment]
This happened to me as well in lab 01. The problem is that the DimCustomer.**fmt** file is missing int the folder /Allfiles/labs/01/data

The file can be found in lab 08 Allfiles/labs/08/data/DimCurrency.fmt

**Comment by GraemeMalcolm** [comment]
Ah - I see it now. Thanks @molenaar and @weslbo 
Should be working now.
