### ISSUE TITLE
Lab 10 Build a data pipeline in Azure Synapse Analytics

### ISSUE THREAD

**Issue by suketunayak** [MicrosoftLearning/dp-203-azure-data-engineer#100]
# Module: 05
#### Step: 03 Linked Service Name: Data_Warehouse

Description of issue - **Test Connection Fails** if we not select Version = Legacy Radio Button mentioned in below screenshot.
This new UI Changes, we have to add in instructions for students. If we do not select Legacy than Test Connections Fails...

![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/12823966/a2f46dae-9e8a-4ed0-97c5-b4e42531435e)

Repro steps:
This new UI Changes, we have to add in instructions for students. If we do not select Version = Legacy (Radio Button) than Test Connections Fails...

**Comment by TheJamesHerring** [comment]
Thanks, step added.
