### ISSUE TITLE
resource-group prefix is incorrect

### ISSUE THREAD

**Issue by parveenkrraina** [MicrosoftLearning/dp-203-azure-data-engineer#105]
# Module: 01
#### Step: 01

Description of issue

Repro steps:

1. name of the resource group started with dp500-xxxx
2. Script is generating the resource-group name as dp000
3. Please update the instructions or script accordingly.

**Comment by TheJamesHerring** [comment]
Will fix, this was an emergency move. Thanks.
JH

**Comment by TheJamesHerring** [comment]
Corrected to be less generic.
