### ISSUE TITLE
Purview Lab - cannot create multiple instances

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/dp-203-azure-data-engineer#107]
# Lab/Demo: 22 - Use Microsoft Purview with Azure Synapse Analytics

Description of issue:

Microsoft Purview cannot be set up multiple times in the same tenant any longer.  When multiple students try to set up Purview in a hosted lab environment it doesn't work.

Therefore, I think this lab should either be flagged as demo only, or removed.

**Comment by GraemeMalcolm** [comment]
There's already a note to that effect.
Different ALHs may use different approaches to providing subscriptions, and the exercise is also used by self-paced learners using a BYO subscription approach - hence not retiring the lab altogether.
