### ISSUE TITLE
Wrong instructions of Lab 2

### ISSUE THREAD

**Issue by usamabinrauf** [MicrosoftLearning/dp-203-azure-data-engineer#112]
# Module: Model, query, and explore data in Azure Synapse
### Description of issue
The instructions for **Lab 2** (file name: "**02-Analyze-data-with-sql**") in the **DP-203** course should have been derived from **Lab 1** (file name: "**01-analyze-data-with-sql**") of the **DP-500** course, as they were several months ago.

Currently, the instructions for **Lab 2** (file name: "**02-Analyze-data-with-sql**") and **Lab 5** (file name: "**05-Analyze-files-with-Spark**") in **DP-203** are identical. This is because **Lab 2** (file name: "**02-Analyze-data-with-sql**") has been mistakenly based on **Lab 2** (file name: "**02-analyze-files-with-Spark**") from the **DP-500** course.

Please correct these inconsistencies.

**Comment by GraemeMalcolm** [comment]
Reverted to the SQL lab insructions
