### ISSUE TITLE
where are the 16 pipelines in exercise 8 

### ISSUE THREAD

**Issue by VireshDoshi** [MicrosoftLearning/dp-203-azure-data-engineer#116]
**Description of issue**
I can't see where th 16 ingestion pipelines are that are referenced in the exercise:
https://learn.microsoft.com/en-us/training/modules/survey-components-of-azure-synapse-analytics/8-exercise-identifying-pipeline-components

**Comment by GraemeMalcolm** [comment]
@TheJamesHerring , I believe this module should have been retired.

**Comment by VireshDoshi** [comment]
Thanks for the respose

**Comment by TheJamesHerring** [comment]
Retiring
