### ISSUE TITLE
Table contains unsupported columns - lab 15

### ISSUE THREAD

**Issue by VireshDoshi** [MicrosoftLearning/dp-203-azure-data-engineer#117]
# Module: 00
#### Step: Create a link connection

Description of issue
The link service between SQL database and Synapse shows errors like these:

SalesLT.Customer
Table contains unsupported columns(NameStyle(bit<UDT>), FirstName(nvarchar<UDT>), MiddleName(nvarchar<UDT>), LastName(nvarchar<UDT>), Phone(nvarchar<UDT>)). Those columns will not be replicated to Azure Synapse Analytics.

SalesLT.Product
Table contains unsupported columns(Name(nvarchar<UDT>)). Those columns will not be replicated to Azure Synapse Analytics. 

Table contains unsupported columns(OnlineOrderFlag(bit<UDT>), PurchaseOrderNumber(nvarchar<UDT>), AccountNumber(nvarchar<UDT>)). Those columns will not be replicated to Azure Synapse Analytics

There are also these errors
Use heap table when your data contains varchar(max), nvarchar(max), and varbinary(max)

Repro steps:

1. follow the steps  on the lab to Create a link connection
1. when you get to the link service replication under Integrate , you will see errors as noted above
1.

**Comment by TheJamesHerring** [comment]
Can you provide screenshots? Nothing has changed on this lab in some time.
