### ISSUE TITLE
lab 10 pipeline  running issues with stage_products 

### ISSUE THREAD

**Issue by VireshDoshi** [MicrosoftLearning/dp-203-azure-data-engineer#118]
# Module: 00
#### Step: 00

Description of issue
When I run the pipeline under monitor, I get the following error around staging_

Operation on target LoadProducts failed: {"StatusCode":"DFExecutorUserError","Message":"Job failed due to reason: at Source 'ProductTable': CREATE EXTERNAL TABLE AS SELECT statement failed as the path name 'abfss://files@datalakerwe6ojg.dfs.core.windows.net/stage_products/5dab94e56b2f44b1ab2837fbf6a19d74/' could not be used for export. Please ensure that the specified path is a directory which exists or can be created, and that files can be created in that directory.","Details":"shaded.msdataflow.com.microsoft.sqlserver.jdbc.SQLServerException: CREATE EXTERNAL TABLE AS SELECT statement failed as the path name 'abfss://files@datalakerwe6ojg.dfs.core.windows.net/stage_products/5dab94e56b2f44b1ab2837fbf6a19d74/' could not be used for export. Please ensure that the specified path is a directory which exists or can be created, and that files can be created in that directory.\n\tat shaded.msdataflow.com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)\n\tat shaded.msdataflow.com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1673)\n\tat shaded.msdataflow.com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:907)\n\tat shaded.msdataflow.com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:802)\n\tat shaded.msdataflow.com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7627)\n\tat shaded.msdataflow.com.microsoft.sqlserver.jdbc.SQLServerC"}

Repro steps:

1. follow the steps in teh Lab
1. run the pipeline under monitor
1. notice the error

**Comment by TheJamesHerring** [comment]
Hi @VireshDoshi, is this being run in an instructor-led class with the provided VMs or on your own machine? I will take a look at this in the mean time.

**Comment by VireshDoshi** [comment]
> Hi @VireshDoshi, is this being run in an instructor-led class with the provided VMs or on your own machine? I will take a look at this in the mean time. 

Hi
Thanks for the reply. 

This is being run on my own machines in azure. I just managed to get this working by deselecting the staging option but no joy when staging option is selected.
