### ISSUE TITLE
Databricks Build data pipeline in this lab fails with Waiting for resources

### ISSUE THREAD

**Issue by VireshDoshi** [MicrosoftLearning/dp-203-azure-data-engineer#119]
# Module: 00
#### Step: 00

Description of issue
Databricks Build data pipeline in this lab fails to execute the delta live pipeline. After hitting start, the pipeline sits in the state "Waiting for resources"

https://microsoftlearning.github.io/mslearn-databricks/Instructions/Exercises/LA-05-Build-data-pipeline.html

Repro steps:

1.follow as above
1.
1.

**Comment by TheJamesHerring** [comment]
Can you provide the lab environment (image) you're using? there's an information button in the top right. I know we're investigating the class of machine for the cluster due to policy changes.

**Comment by TheJamesHerring** [comment]
un-repeatable in dev and ILT environments. I will monitor and address if I see an issue.
