### ISSUE TITLE
permission denied on setup.ps1

### ISSUE THREAD

**Issue by issamqasas** [MicrosoftLearning/dp-203-azure-data-engineer#121]
# Module: 00
#### Step: 00

Description of issue
lab09 , when trying to execute the ./setup.ps1 --> gave the following error: Permission denied on setup.ps1
Repro steps:

1.
1.
1.

**Comment by TheJamesHerring** [comment]
No response, assume the problem was transient or regional and has resolved itself. We were unable to repeat on this end.
