### ISSUE TITLE
Spark version error in Allfiles/labs/04/setup.json template

### ISSUE THREAD

**Issue by JBeumala-Dignitae** [MicrosoftLearning/dp-203-azure-data-engineer#124]
Description of issue
In the ARM template used in lab 04, on line 56 we define a variable for the Spark Version to use: "sparkVersion": "3.1"

This version is unsupported from January 26, 2024, and the deployment is not creating the Spark pool with this clear error: Spark Compute version: 3.1 is invalid (Code: InvalidSparkComputeVersion)

Please update the sparkVersion variable on line 56 to 3.4

Many Thanks

**Comment by TheJamesHerring** [comment]
Change made, checking deployment script now.
