### ISSUE TITLE
Real time streaming tile not working

### ISSUE THREAD

**Issue by asenclara** [MicrosoftLearning/dp-203-azure-data-engineer#129]
## Lab/Demo: Lab 19

Description of issue:
When trying to use a real time semantic model in a dashboard, the following error appears:
"This feature is no longer available - You can no longer create real-time semantic models in Power BI, and existing streaming models will be retired soon"

Instead, it is suggested to use Real-Time intelligence in Fabric
https://powerbi.microsoft.com/blog/announcing-the-retirement-of-real-time-streaming-in-power-bi/

**Comment by aleksis-j** [comment]
Same issue for Lab 19 
https://microsoftlearning.github.io/dp-203-azure-data-engineer/Instructions/Labs/19-Stream-Power-BI.html
