### ISSUE TITLE
Lab 18 - year is hardcoded in the script

### ISSUE THREAD

**Issue by aleksis-j** [MicrosoftLearning/dp-203-azure-data-engineer#131]
#### Step: Run the streaming job to aggregate order data

Description of issue 
Streaming job will generate data using current date, but script in step 7 has '2023' hardcoded and will fail.

https://microsoftlearning.github.io/dp-203-azure-data-engineer/Instructions/Labs/18-Ingest-stream-synapse.html

**Comment by TheJamesHerring** [comment]
Step 7, when copied using the tool, is editable by using the top row of the keyboard below the function keys. That said, it's aways a good practice to type the code out when learning a language to help build muscle memory and process it as you type.
