### ISSUE TITLE
Capacity Issues in Databricks Labs

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/dp-203-azure-data-engineer#132]
# Lab 19: Use Spark in Azure Databricks
# Lab 21: Use a SQL Warehouse in Azure Databricks

(Probably all the databricks labs, but I haven't tried them all yet.)

Description of issue:

- I don't believe this is a GitHub / Scripting issue; I believe it is on the Lab Hoster side, which is Skillable / Learn on Demand.  
- I believe this because the scripts work fine in a few different "private" subscriptions, but always fail in the Skillable subscriptions

- For any of the Databricks labs, the script will always fail with an error:

`QUOTA_EXCEEDED: Cannot have more than 10000 users and service principals in one account`

- Then, after the scripts finish, if you go to the Databricks resource, you see the message `The workspace 'databricks16z0vkn' is in a failed state and cannot be launched. Please review error details in the activity log tab and retry your operation. `

I believe the Skillable system isn't "pruning" out the old accounts or however they setup their labs.

Also, if I try to create a databricks instance manually, it fails with the same error.

I've attached two file that show the output when you run the script and when you try to create databricks manually.

[Error when Building Manually.txt](https://github.com/user-attachments/files/17774796/Error.when.Building.Manually.txt)
[Output of the Script.txt](https://github.com/user-attachments/files/17774797/Output.of.the.Script.txt)

**Comment by GraemeMalcolm** [comment]
The Skillable team is aware and are actively investigating the issue.

**Comment by TheJamesHerring** [comment]
This has been resolved according to Skillable.
