### ISSUE TITLE
Microsoft.Sql Resource Provider not registering fast enough - Script fix

### ISSUE THREAD

**Issue by rob-foulkrod** [MicrosoftLearning/dp-203-azure-data-engineer#135]
# Module: all
## Lab/Demo: all

Description of issue
It is a common issue when help students with labs to see the install of Synapse has failed. The most common issue that I see, (when learners still have to console open, is that the Microsoft.SQL resource provider is not registered. The script starts the registration, but we end up with an unfortunate race condition where Synapse begins installing before the registration has completed.

I suggest we add a verification step to the install script that looks like this...

```powershell
$maxRetries = 5
$waittime = 30
foreach ($provider in $provider_list) {
    $retryCount = 0
    while ($retryCount -lt $maxRetries) {
        $currentStatus = (Get-AzResourceProvider -ProviderNamespace $provider).RegistrationState
        if ($currentStatus -eq "Registered") {
            Write-Host "$provider is successfully registered."
            break
        }
        else {
            Write-Host "$provider is not yet registered. Waiting for $waitTime seconds before rechecking..."
            Start-Sleep -Seconds $waitTime
            $retryCount++
        }
    }
    if ($retryCount -eq $maxRetries) {
        Write-Host "Failed to register $provider after $maxRetries attempts."
    }
}
```

This script uses the same $provider_list variable that stores the names of the providers and will wait and recheck until the providers have completed. This should reduce the number of failed lab installs.

**Comment by rob-foulkrod** [comment]
If there is becomes an accepted idea, I can submit a pull request. I know there is risk as this could potentially affect every lab.

**Comment by TheJamesHerring** [comment]
It's not the script, but the registration process itself. It sometimes requires it to be run more than once in PS. That said, I will put the try..catch in the code to see if it helps.
JH
