### ISSUE TITLE
Update instructions to say legacy dashboard instead of dashboard

### ISSUE THREAD

**Issue by gyancloud** [MicrosoftLearning/dp-203-azure-data-engineer#137]
# Module: Use SQL warehouse in Azure databricks
### Task: Create a Dashboard

Description of issue
The instructions reference creating a dashboard with steps that worked on an old version of databricks. Since a new release the dasboarding capabilities of databricks have expanded and the instructions do not work anymore. It should mention that you need to create a _legacy_ dashboard. Then all the instructions can stay the same. 
Repro steps:
1. Do the lab
1. Make a dashboard

**Comment by GraemeMalcolm** [comment]
Updated to new Databricks labs
