### ISSUE TITLE
Lab01 : Ressource managers not automatically registered

### ISSUE THREAD

**Issue by MaximeRCD** [MicrosoftLearning/dp-203-azure-data-engineer#139]
# Module: AllFiles
#### Step: # Register resource providers

Description of issue

I have a newly created account with pay as you go Azure Plan. I am owner of the tenant and the subscription.

I tried to follow lab01 of the https://microsoftlearning.github.io/[dp-203-azure-data-engineer](https://microsoftlearning.github.io/dp-203-azure-data-engineer/Instructions/Labs/01-Explore-Azure-Synapse.html)/Instructions/Labs/01-Explore-Azure-Synapse.html

When launching setup.ps1, no resource provider was registered and the script only checks if some are already registered but do not actually register them if it is not the case. 

I was urged to go to my subscription under the parameters/ressources manager to manually register each of the four resource managers. 

Then applying setup.ps1 worked. 

To close this issue maybe add a step to register the needed ressource managers inside line 75 to 92.

**Comment by craigbeeremct** [comment]
This error happened this morning. Several students had to run the code twice. For one of the students, I had to remotely control thei lab and manually register Microsoft.Synapse, Microsoft.Compute, and Microsoft.SQL.

Maybe we go back to the manual steps of "Register-AzResourceProvider" then running "Get-AzResourceProvider | ft *State" until they all show 'registered'?
