### ISSUE TITLE
Minor: Lab 7 creates RG DP000****** instead of DP203******

### ISSUE THREAD

**Issue by douwevandenberg** [MicrosoftLearning/dp-203-azure-data-engineer#14]
# Module: 00
#### Step: 05

Description of issue
Running the setup for the lab "Use Delta Lake with Spark in Azure Synapse Analytics" created a DP000****** resource group for me, instead of DP203. It's just a naming issue and I'm sure people will be able to spot the correct resource group. But the instructions do mention DP203*****, which is false.

Repro steps:

1. run the setup in step 5.

**Comment by GraemeMalcolm** [comment]
Thanks @douwevandenberg - fixed!
