### ISSUE TITLE
15-Synapse-link-sql.md - replace SQL Database with SQL Server

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/dp-203-azure-data-engineer#18]
# 15-Synapse-link-sql.md
#### Step: 1

In the paragraph:

> In the page for your Azure SQL Database resource, in the pane on the left, in the Security section (near the bottom), select Identity. Then under System assigned managed identity, set the Status option to On. Then use the 🖫 Save icon to save your configuration change.

Replace "Azure SQL Database resource" with "Azure SQL Server resource".

**Comment by GraemeMalcolm** [comment]
Thanks @craigbeeremct - fixed
