### ISSUE TITLE
Incorrect instructions Lab 27

### ISSUE THREAD

**Issue by parveenkrraina** [MicrosoftLearning/dp-203-azure-data-engineer#19]
# Module: 27
#### Step: Generate an access token

Description of issue: it says click on, In the Azure Databricks portal, at on the **top left** menu bar, select the username and then select User Settings from the drop-down.

Whereas it should be **top right** menu bar, please check and update.

**Comment by GraemeMalcolm** [comment]
Thanks @parveenkrraina - fixed.
