### ISSUE TITLE
Lab 03 CSV Header Row Missing

### ISSUE THREAD

**Issue by francocalvo** [MicrosoftLearning/dp-203-azure-data-engineer#22]
#### Step: 06

When I executed the PS script, it created everything fine, but apparently, the CSV files don't have the header row. I had to delete them, and upload the versions that are in this repo.

**Comment by GraemeMalcolm** [comment]
Are you sure you ran the setup script for Lab 3 (not 4)? The script for Lab 3 uploads the files [here](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/tree/master/Allfiles/labs/03/data), which include the header.

**Comment by francocalvo** [comment]
I'll check tomorrow again, but I copy pasted the commands directly, so it shouldn't be that. I'll keep you posted :)

**Comment by GraemeMalcolm** [comment]
@francocalvo , were you able to repro the issue?

**Comment by GraemeMalcolm** [comment]
Closing as non-repro
