### ISSUE TITLE
Instructions need Updated from "File" to "Generic Protocol"

### ISSUE THREAD

**Issue by Jason-Microsoft-MTT** [MicrosoftLearning/dp-203-azure-data-engineer#23]
# Module: 01
#### Step: 03

Description of issue

Instructions state to navigate to the File tab to get the HTTP icon. HTTP isnt under File, its under Generic Protocol - needs updated 
<img width="463" alt="image" src="https://user-images.githubusercontent.com/120508481/232620601-c8707df5-2d49-4659-926c-f7993782f0cd.png">

<img width="477" alt="image" src="https://user-images.githubusercontent.com/120508481/232620659-a664803b-f598-4236-90c9-de55d7b41eed.png">

Repro steps:

1.
1.
1.

**Comment by GraemeMalcolm** [comment]
Thanks @Jason-Microsoft-MTT - Fixed.
