### ISSUE TITLE
Provision an Azure Synapse Analytics workspace asks for adxPoolName and uniqueSuffix

### ISSUE THREAD

**Issue by parveenkrraina** [MicrosoftLearning/dp-203-azure-data-engineer#29]
# Module: 01
#### Step: 05

Description of issue
When running the setup.ps1 script, it asks for adxPoolName and uniqueSuffix. It is not mentioned in the instructions.
Please investigate the issue.

**Comment by TheJamesHerring** [comment]
ADX has been removed from this lab, the issue has been resolved.
