### ISSUE TITLE
No datasets were found

### ISSUE THREAD

**Issue by ralsouza** [MicrosoftLearning/dp-203-azure-data-engineer#33]
# Module: 06
#### Step: 4

There is no returned data.

Warning: No datasets were found that match the expression 'RetailDB.dbo.Customer'.

Statement ID: {6D97EB15-84E0-4C75-BDD6-151350430D34} | Query hash: 0xC74B9B855CD85610 | Distributed request ID: {E9E904AE-6014-4F0B-A94F-8E622319E868}. Total size of data scanned is 0 megabytes, total size of data moved is 0 megabytes, total size of data written is 0 megabytes.
(0 record affected)

Total execution time: 00:00:11.455

Repro steps:

1. In the main pane, switch back to the files tab, which contains the file system with the RetailDB folder. Then open the RetailDB folder and create a new folder named Customer in it. This is where the Customer table will get its data.

2. Open the new Customer folder, which should be empty.

3. Download the customer.csv data file from https://raw.githubusercontent.com/MicrosoftLearning/dp-203-azure-data-engineer/master/Allfiles/labs/04/data/customer.csv and save it in a folder on your local computer (it doesn't matter where). Then in the Customer folder in Synapse Explorer, use the ⤒ Upload button to upload the customer.csv file to the RetailDB/Customer folder in your data lake.

4. In the Data pane on the left, on the Workspace tab, in the ... menu for the Customer table, select New SQL script > Select TOP 100 rows. Then, in the new SQL script 1 pane that has opened, ensure that the Built-in SQL pool is connected, and use the ▷ Run button to run the SQL code. The results should include first 100 rows from the Customer table, based on the data stored in the underlying folder in the data lake.

**Comment by GraemeMalcolm** [comment]
@TheJamesHerring - Can you investigate and try to repro?

**Comment by TheJamesHerring** [comment]
Taking a look now, will post findings.

**Comment by TheJamesHerring** [comment]
Issue resolved - please let me know if you have any other issues.

**Comment by ralsouza** [comment]
Hi, thanks!

I can't get any data, even changing the authentication method.

I tried with Pyspark and got the same results.

`%%pyspark`
`df = spark.sql("SELECT * FROM `RetailDB`.`Customer`")`
`df.show(10)`


+-----------+----------+----------+--------------+------+
|CustomerId|FirstName|LastName|EmailAddress|Phone|
+-----------+----------+----------+--------------+------+
+-----------+----------+----------+--------------+------+

**Comment by lyb53708621** [comment]
Meet the same issue.
"External table 'RetailDB.dbo.Customer' is not accessible because content of directory cannot be listed."
