### ISSUE TITLE
Script error where notebooks don't execute due to unauthorised IP address 

### ISSUE THREAD

**Issue by VEshelbyMTT** [MicrosoftLearning/dp-203-azure-data-engineer#35]
# Module: 6/3
#### Step: 8 

Description of issue

The following error has appeared twice this week for two people in the course I'm teaching where they run the script that requires a spark notebook and receive an error in the setup script. I want to make you aware that not all ip addresses are accepted and it will need to be manually declared in the setup script.  

Appears in cloud shell prompt. E.g.: 

```
Importing Spark Transform.ipynb ...
ERROR: (ClientIpAddressNotAuthorized) Client Ip address : 13.73.***.**
Code: ClientIpAddressNotAuthorized
Message: Client Ip address : 13.73.***.**
Script completed at 05/31/2023

```

Temp fix: 
github repo -> allfiles/lab -> lab number you're in -> notebooks -> save notebook as rawfile (.ipynb) + ensuring no additional extensions added e.g. '.txt'. -> in synapse, import file -> publish. 

Repro steps:

1. allow all IP address or search to find current IP address and enable (not sure exactly where in the setup scripts) in the ps script

**Comment by GraemeMalcolm** [comment]
I address permissions are not set in the script. By default, the cloud shell address should have access - I suspect this is actually a capacity issue in the Azure datacenter.
