### ISSUE TITLE
Lab 6 - Transform Spark notebook not importing into WS

### ISSUE THREAD

**Issue by Jason-Microsoft-MTT** [MicrosoftLearning/dp-203-azure-data-engineer#36]
# Module: 03
#### Step: 00

I have been noticing that the Transform Spark notebook has not been importing into the workspace.

Repro steps:

1.
1.
1.

**Comment by TheJamesHerring** [comment]
I've changed this to where the user should now have a link to download ipynb (python notebook) file and save it locally to prevent issues of Powershell not importing into Synapse properly. This has been tested and works. Please let me know if you see anything amiss. JH
