### ISSUE TITLE
Lab 14 - Sweden Central is not available yet for Synapse

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/dp-203-azure-data-engineer#37]
# Module: 00
#### Step: 5 (./setup.ps1)

Description of issue

- Synapse is not available yet in swedencentral. We had a learner this week who noticed that not all resources were deployed after running the setup script. I noticed that region swedencentral was used. According to [Products available by region](https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/?products=synapse-analytics&regions=non-regional,sweden-central,sweden-south) it will come in Q3 2023.

Repro steps:
just follow instructions

**Comment by GraemeMalcolm** [comment]
I removed the swedencentral region from the options in the script
