### ISSUE TITLE
dp-203-azure-data-engineer/Instructions/Labs /22-Synapse-purview.md /Step 05

### ISSUE THREAD

**Issue by Nimra-Maryam** [MicrosoftLearning/dp-203-azure-data-engineer#38]
# Module: 22
## Step: 05

An error occurs when we run the commands "cd dp-203/Allfiles/labs/22" "./setup.ps1" that Database 'lakedb' does not exist.
Due to this, we couldn't get lakedb serverless SQL pool in further next steps.

![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/133017642/5bf2a171-a15c-4ecf-ac79-282a60b24a44)

![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/133017642/2f3d8181-02bc-48ec-81ba-969c0e01fa3d)

**Comment by GraemeMalcolm** [comment]
@TheJamesHerring - I can repro this. What *seems* to be happening is that there's some internal operation in the **model** database that prevents the CREATE DATABASE statement getting an exclusive lock - likely an unclosed session from the initial serverless pool creation. It may be that waiting and retrying fixes it, or it might be more reliable to just add steps to have the learner run the SQL code to create the databases interactively at the beginning of the lab (and remove the section of the script that creates the databases).

**Comment by TheJamesHerring** [comment]
I'll take a look ASAP, thanks @GraemeMalcolm for the repro feedback. JH

**Comment by aparnakhadatkar** [comment]
@GraemeMalcolm @TheJamesHerring -- I have faced the same issue while performing lab 22 today. Can you please provide me with updates on this? Is this issue got resolved?

**Comment by TheJamesHerring** [comment]
Unable to repeat this error and this may have been related to a bug that was caught last week. I have our tester also verifying in another random region. I tested in 'westeurope' and eastus.

![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/49248205/b78056f7-63ab-4480-a274-bdde1aeb06be)

Display of the database named: lakedb.

![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/49248205/ac6ff438-46a0-4ac3-b917-f99bda8b6e44)

**Comment by aparnakhadatkar** [comment]
Thanks for the update @TheJamesHerring

**Comment by neelotpalchaulia** [comment]
@TheJamesHerring 
The issue still persists. I did try to manually set the region to "westeurope" and "eastus".
The issue seems to be persistent.

**Comment by TheJamesHerring** [comment]
I will have another look, I just closed the ticket with engineering yesterday.

**Comment by asenclara** [comment]
I am also facing the same issue today. I am using "west europe"
