### ISSUE TITLE
Repository question

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/dp-203-azure-data-engineer#4]
Hi all,

Just got 2 questions in mind.

1. Which repository should the lab hosters be using for the course DP-203?

2. What is the difference between this repository and the one in the link below:
https://github.com/MicrosoftLearning/DP-203-Data-Engineer

Any help will be greatly appreciated thanks!

**Comment by GraemeMalcolm** [comment]
This one will replace the existing one in the next release - it's currently pre-release
