### ISSUE TITLE
Missing /files/data/Product.csv file

### ISSUE THREAD

**Issue by ralsouza** [MicrosoftLearning/dp-203-azure-data-engineer#40]
# Module: Load Data into a Relational Data Warehouse
#### Step: 03

Description of issue
There is no file Product.csv in https://datalakexxxxxx.blob.core.windows.net/files/data/
Repro steps:

1. Open [Load data from a data lake by using the COPY statement](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/blob/master/Instructions/Labs/09-Load-Data-into-Data-Warehouse.md#load-data-from-a-data-lake-by-using-the-copy-statement)
2. Follow the tutorial

**Comment by GraemeMalcolm** [comment]
The file is uploaded by the setup script - did you receive any errors when running setup.ps1?

**Comment by TheJamesHerring** [comment]
No issues in testing.
