### ISSUE TITLE
Creating lake database does not initalise GUI in synapse

### ISSUE THREAD

**Issue by VEshelbyMTT** [MicrosoftLearning/dp-203-azure-data-engineer#41]
# Module: 00
#### Step: 6

Description of issue
A learner has reported they are unable to open the lake database in the lab. 

Current detour is to go through the knowledge center and set up table, continue with the steps for table_1, then delete the table afterwards. 

Repro steps:

using my own environment, I am also able to recreate this same error: ![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/104829457/7ad8e85c-3584-47ca-9f16-0fba8c4b4c92) ![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/104829457/4fc28ffc-07d8-42fa-aea5-9ee1fe5236fc)

**Comment by TheJamesHerring** [comment]
BTW, were others within the training able to?

**Comment by VEshelbyMTT** [comment]
following the steps from the knowledge center, yes. But the vocal learners (4) experienced the exact same white screen as shared in the screenshot.

________________________________

**Comment by TheJamesHerring** [comment]
Opened ticket with engineering and problem has been resolved.
