### ISSUE TITLE
404 link in exercise 25 instructions

### ISSUE THREAD

**Issue by lgvacanti** [MicrosoftLearning/dp-203-azure-data-engineer#42]
# Module: 25
#### Step: 7

Description of issue

The Introduction to Delta Lake link in the instructions for Exercise 25 (Instructions/Labs/25-Delta-lake-in-Azure-Databricks.md) leads to a 404 page:
[Introduction to Delta Lake](https://docs.microsoft.com/azure/databricks/delta/delta-intro)

**Comment by GraemeMalcolm** [comment]
Thanks. I updated the link.
