### ISSUE TITLE
Lab 04, missing RetailDB directory inside deployed SA

### ISSUE THREAD

**Issue by MarkSaf17** [MicrosoftLearning/dp-203-azure-data-engineer#43]
# Module:  Analyze data in a lake database
#### Step: 00

Description of issue:

I followed the instruction for 4th lab, but after successfully executed setup script - there is no RetailDB directory inside StorageAccount.
As I understand its required.

Script was executed 2 times and deployed resources(AzureSynapse/SA) in different regions(WestEurope, NorthEurope).
Stdout for last script run in attach.

Please help me to fix that, and text me if you need Additional info from my side.

Thanks in advance!

[setup_stdout.txt](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/files/11793967/setup_stdout.txt)
 
<img width="1493" alt="image" src="https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/136630570/f61ee3c3-0ffd-4955-9bb1-0c9b106a51e4">
<img width="1499" alt="image" src="https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/136630570/8b8595f3-c7a2-4a8b-a6b8-f2b2a2da5c6c">

**Comment by GraemeMalcolm** [comment]
@TheJamesHerring, can you take a look at this and see if it's a repeat of the issue you previously resolved?

**Comment by MarkSaf17** [comment]
> @TheJamesHerring, can you take a look at this and see if it's a repeat of the issue you previously resolved?

Hi!

sorry, can you give me the link to same issue if you have?
I tried to find something similar, but I cant

**Comment by TheJamesHerring** [comment]
@MarkSaf17 this is an issue with the screenshot I included for a workaround, which I'll update. You will create the directory and the lake database in the steps after the screenshots starting here: https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/blob/master/Instructions/Labs/04-Create-a-Lake-Database.md#create-a-lake-database

**Comment by MarkSaf17** [comment]
@TheJamesHerring 
Oh sorry, it was my bad. I met some troubles in next step yesterday and decided that its problems with setup script. 

Thanks!
