### ISSUE TITLE
Cannot provision databricks workspace using setup script. 

### ISSUE THREAD

**Issue by ricardvalc** [MicrosoftLearning/dp-203-azure-data-engineer#45]
# Module: Explore Azure Databricks
#### Step: 00

Description of Issue: 

Hi! I am having some issues when following the instructions for the 'Explore Azure Databricks' exercise. 

I manage to clone the repo using the Powershall pane as usual, but after changing the folder and running the script I get an error, and in the end no Databricks workspace is created or anything else for that matter (no resource group or otherwise). 

After running the setup scrip this is the messages I receive on screen 

<img width="318" alt="error" src="https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/111350442/c7fdd22b-cb82-4cb2-9fe1-286418da2f41">

I'm not sure exactly where the problem lies, so any advice is welcome! If you need more information, let me know!

Hopefully someone can help. Thanks in advanced

**Comment by TheJamesHerring** [comment]
This appears to be a constraint on either the compute or the Databricsk service in the regions. I saw the error one time but it did successfully build in Eastasia. I'm not sure of the type of Subscription you have, but if possible try building manually in eastasia.

![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/49248205/2280ea21-45d9-43b2-a766-eb1534ca0ea9)

This should help with a manual setup of Azure Databricks where you can select the region:
https://learn.microsoft.com/en-us/azure/databricks/getting-started/#use-the-portal-to-create-an-azure-databricks-workspace
