### ISSUE TITLE
Gitlab 17/ VM lab 14 throws significant errors due to managed identity not assigning correctly to eventhub

### ISSUE THREAD

**Issue by VEshelbyMTT** [MicrosoftLearning/dp-203-azure-data-engineer#46]
# Module: 00
#### Step: 00

Description of issue

Repro steps:

Multiple Users report this issue:
![MicrosoftTeams-image (13)](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/104829457/0035f304-209b-4ce2-bf34-f07482b8aff3)

so we run and they then get permissions issues

<img width="729" alt="MicrosoftTeams-image (15)" src="https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/104829457/f53d0c64-bd0b-4a54-9907-f489bbcfe6f2">

**managed identity was not assigned to the event hub** 

Thus: 
https://learn.microsoft.com/en-us/azure/stream-analytics/event-hubs-managed-identity

Solution: 
1. Create a new input
2. Assigned managed identity from SA to Event hub analytics 'Azure Event Hubs Data Owner'
3. run
4. ignore all notifcations and check SA
![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/104829457/c5281ffb-63b2-41f3-8f74-534bf633936f)

Can we add the permission to Eventhubs in the PS script?

**Comment by GraemeMalcolm** [comment]
I've only ever seen this if you don't follow the instruction to "Wait for a Successful connection test notification".
Are you saying they received a success notification but the permissions still hadn't propagated? If so, that's a bug in the product.

**Comment by VEshelbyMTT** [comment]
They receive a successful notification with the new input in place and still receive this error.

________________________________

**Comment by TheJamesHerring** [comment]
I just went through this, and if there is a problem with setting the managed identity automatically, it provides a link to the appropriate document in the message, which adds about 2 minutes to the lab. It's not a bug with the lab, just a known potential issue with the product that the user can quickly remedy.  JH
