### ISSUE TITLE
databricks - finding uploaded data

### ISSUE THREAD

**Issue by VEshelbyMTT** [MicrosoftLearning/dp-203-azure-data-engineer#47]
# Module: 00
#### Step: 00

Description of issue
users having difficulty finding uploaded data  - make it a little more general and have them enable the DBFS file store in the admin settings console. 

solution: 

If you have uploaded the data but cannot find it in the data. 

 Note:  Data must be uploaded already 

 Any errors you face afterwards:  
![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/104829457/371a0f4c-a612-4464-9474-6b694d294fee)

enable DBFS file store in your admin console 
![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/104829457/a43964c7-842a-4716-a513-0b9158ae37c8)

 then refresh and return to your notebook 
![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/104829457/cb0d3f5e-8941-4709-a2c5-e7097f09910b)

Find your file using the DBFS explore -> right click and copy the file path  

Note: you may have to do a bit of digging based on where you uploaded your data but it should be there. Otherwise, you can always add it again. 

  

REPLACE THE FOLLOWING CODE 

filepath = #INSERT YOUR FILEPATH  
df1 = spark.read.format("csv").option("header", "true").load(filepath)

**Comment by TheJamesHerring** [comment]
Please note: this is not a bug. We can't account for user error or not remembering where they uploaded their file(s) to. The MCT/MTT should be guiding the learners on the caveats of copying and remembering where they may have placed a file.

**Comment by VEshelbyMTT** [comment]
The file does not show up for them as dbfs doesn't show them where they can access the txt file.

________________________________

**Comment by TheJamesHerring** [comment]
Re-opened - looks like a chane to Databricks.

**Comment by TheJamesHerring** [comment]
I went through this twice and intentionally didn't copy the code as directed by the directions to 'lose' where it might be located. The best fix is to take a step back and start with the File..Upload data to DBFS... step again to correct versus going through the process outlined above. There is no bug with this lab.
