### ISSUE TITLE
Lab 22 (synapse and purview) no longer works at powershell script launch - high importance

### ISSUE THREAD

**Issue by VEshelbyMTT** [MicrosoftLearning/dp-203-azure-data-engineer#48]
# Module: 00
#### Step: 00

Description of issue

![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/104829457/85e2d8dc-214e-41c4-a873-f881c58bab39)

I was able to immediately experience the problem on my own environment . The template is the cause of it. 

`New-AzResourceGroupDeployment: /home/user1-32139270/dp-203/Allfiles/labs/22/setup.ps1:142
Line |
 142 |  New-AzResourceGroupDeployment -ResourceGroupName $resourceGroupName `
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 6:56:26 AM - Error: Code=InvalidTemplateDeployment; Message=The template deployment 'setup' is not valid according to the validation procedure. The tracking id is 'af939892-c675-4780-ba72-f75044dbfdb2'. See inner errors for
     | details.
New-AzResourceGroupDeployment: /home/user1-32139270/dp-203/Allfiles/labs/22/setup.ps1:142
Line |
 142 |  New-AzResourceGroupDeployment -ResourceGroupName $resourceGroupName `
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 6:56:27 AM - Error: Code=35001; Message=Validation failed for purview1jtdza6. A Tenant-level Purview Account already exists for tenant: LODS-Prod-MSLearn-MCA with ID: bb7ed293-2674-4aef-a74a-dbf340a8ab33. If you want to create an
     | additional Purview Account, please reach out to Microsoft Support. Correlation ID: af939892-c675-4780-ba72-f75044dbfdb2
New-AzResourceGroupDeployment: /home/user1-32139270/dp-203/Allfiles/labs/22/setup.ps1:142
Line |
 142 |  New-AzResourceGroupDeployment -ResourceGroupName $resourceGroupName `
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The deployment validation failed
Granting permissions on the datalake1jtdza6 storage account...
(you can ignore any warnings!)
New-AzRoleAssignment: /home/user1-32139270/dp-203/Allfiles/labs/22/setup.ps1:160
Line |
 160 |  New-AzRoleAssignment -Objectid $id -RoleDefinitionName "Storage Blob  …
     |                                 ~~~
     | Cannot validate argument on parameter 'ObjectId'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
Loading data to data lake...
Get-AzStorageAccount: /home/user1-32139270/dp-203/Allfiles/labs/22/setup.ps1:165
Line |
 165 |  … geAccount = Get-AzStorageAccount -ResourceGroupName $resourceGroupNam …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The Resource 'Microsoft.Storage/storageAccounts/datalake1jtdza6' under resource group 'dp203-1jtdza6' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix

products.csv
Set-AzStorageBlobContent: /home/user1-32139270/dp-203/Allfiles/labs/22/setup.ps1:172
Line |
 172 |      Set-AzStorageBlobContent -File $_.FullName -Container "files" -Bl …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not get the storage context.  Please pass in a storage context or set the current storage context.
Creating databases...
Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : TCP Provider: Error code 0x2AF9.
Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to synapse1jtdza6-ondemand.sql.azuresynapse.net. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : TCP Provider: Error code 0x2AF9.
Sqlcmd: Error: Microsoft ODBC Driver 18 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to synapse1jtdza6.sql.azuresynapse.net. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
Pausing the sql1jtdza6 SQL Pool...

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
2      Long Running O… AzureLongRunni… Running       True            localhost            Suspend-AzSynapseSqlPool
Script completed at 06/29/2023 06:56:47`
Repro steps:

1.
1.
1.

**Comment by TheJamesHerring** [comment]
Code changes made that convert automated code to manual steps. The changes appear to 1) a modal popup related to a customer disclosure around database templates and 2) resource constraints when deploying purview with the other allocated resources (synapse, lake database, and dedicated SQL pool). Please let me know if you see anything else. Will work on anonymizing screen images asap.
