### ISSUE TITLE
Lab: Transform files using a serverless SQL pool.  Bug in code

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/dp-203-azure-data-engineer#5]
# Module: 2
#### Step: 4

Description of issue
The SQL query returns an error. 

The code block is this one:

```
 SELECT
     TOP 100 *
 FROM
     OPENROWSET(
        BULK 'https://datalakex98z7wc.dfs.core.windows.net/files/sales/csv**',
         FORMAT = 'CSV',
         PARSER_VERSION='2.0'
     ) AS [result]

```

It returns an error:

`Consecutive wildcard characters present in path 'https://datalakex98z7wc.dfs.core.windows.net/files/sales/csv**'.`

If I change the line in question to this (adding a "/" before after the word csv) the query seems to work correctly:
`BULK 'https://datalakex98z7wc.dfs.core.windows.net/files/sales/csv/**',`

**Comment by GraemeMalcolm** [comment]
Your code doesn't match the instructions at https://microsoftlearning.github.io/DP-500-Azure-Data-Analyst/Instructions/labs/01-analyze-data-with-sql.html.

**Comment by tylerfarmer1** [comment]
I'm referring to this one.  It's Lab 1 in Module 2, which is probably considered Lab 3, sorry about that...

https://microsoftlearning.github.io/dp-203-azure-data-engineer/Instructions/Labs/03-Transform-data-with-sql.html

**Comment by GraemeMalcolm** [comment]
Code runs as expected:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/11771134/219480149-33b76d22-e43b-40ca-b7ca-324fd3775293.png">

**Comment by GraemeMalcolm** [comment]
Ah, I see - you actually typed the code , and the example has a missing / - the instructions are to auto-generate it. I'll fix the sample

**Comment by GraemeMalcolm** [comment]
Fixed
