### ISSUE TITLE
Lab 3 setup failures ( Failed to connect to MSI) 

### ISSUE THREAD

**Issue by romshe** [MicrosoftLearning/dp-203-azure-data-engineer#51]
Lab 3
Description of issue
The setup script runs with an error on step "Granting permissions on the datalake  storage account..." 

Repro steps:

Run the cloudshell setup
Chose my MSDN subscription 

ERROR: Failed to connect to MSI. Please make sure MSI is configured correctly.
Get Token request returned: <Response [400]>
![Screenshot 2023-07-26 135149](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/140607770/67635f0c-c1f9-4a86-a8bd-cc5c8200a9f0)

Could you help me with this error?

**Comment by romshe** [comment]
I am also attaching the entire execution log 
[setup_log.txt](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/files/12171809/setup_log.txt)

**Comment by Mihai-Ac** [comment]
Hi @romshe 

I tried reproducing this issue and I couldn´t get it to appear. The setup ran without any issues.

From what I see, it seems to have something to do with the Managed Service Identity (MSI) in Azure. This kind of error sometimes appears when there are multiple user accounts logged in azure(lets say one personal and a work one). One way to fix this would be to run "az login" first and connect to the correct one (or the one that needs to be used for this exercise).  This will allow you to authenticate to Azure using the Azure CLI.

**Comment by TheJamesHerring** [comment]
Thanks @Mihai-Ac  - I couldn't see a problem either. Note: as Mihai noted, this should be run from Cloudshell.
JH

**Comment by romshe** [comment]
Hi all 
Running "az login" before deploying helps me
Maybe this should be added to the deployment guide, for people who use multiple accounts a lot.
Thanks for the help!
