### ISSUE TITLE
Lab 22 - Synapse and Purview

### ISSUE THREAD

**Issue by athelen20** [MicrosoftLearning/dp-203-azure-data-engineer#52]
# Module: 08
#### Step: 05

Description of issue
Student reports:
SQL table is named dbo.DimProduct instead of dbo.products and the column is not ProductKey but ProductID. 

Please view image
![MicrosoftTeams-image (14)](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/60407620/4fceafbf-f7c9-42fe-a51c-d40ac80084cf)

**Comment by TheJamesHerring** [comment]
Updated in the table creation script, it should be good to go. Please let me know if you have any other problems.
