### ISSUE TITLE
Lab 26(21 in esi) issue. New UI is the default(Databricks) and instructions are based on old UI

### ISSUE THREAD

**Issue by arvie993** [MicrosoftLearning/dp-203-azure-data-engineer#53]
# Module: 00
#### Step: 01

Description of issue
Databricks defaults to its new UI as of late. This has caused some confusion for many of the learners.

Repro steps:

1. Sign to Azure using esilearnondemand 
2. Load the necessary resources through the given Powershell scripts 
3. Start reading instructions on how to view and start the SQL warehouse (instructions won't match the UI because it has been updated by default)

Extra info/solution: 
The instructions on the right are going only to work if you have the old UI. 

You can disable the new UI:

 
![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/72575271/4f8ee09b-d67a-4558-802b-9c859fffb810)

This should ideally be called out going forward.

**Comment by TheJamesHerring** [comment]
This is on task list - will provide update asap.

**Comment by TheJamesHerring** [comment]
Updated. Please let me know if you have any questions.
JH
