### ISSUE TITLE
Lab setup failures

### ISSUE THREAD

**Issue by Derekp20** [MicrosoftLearning/dp-203-azure-data-engineer#6]
Lab 3
Description of issue
The setup script runs with an error when validating the Synapse Workspace. Subscription needs to be registered with the Microsoft.SQL resource provider

When refreshing the Azure portal, only the datalake can be seen.

run the setup a second time, on completion there are 2 resource groups and 2 sets of resources. This has happened to me and to my students.

Repro steps:

1. Run the cloudshell setup
1. Only the resource group and datalake are visible
1. Run the setup a second time resources created sucessfully
2. 
![image](https://user-images.githubusercontent.com/38468752/220161933-9829cd12-8c0c-4fb2-9de6-da6f09202c8d.png)

This using Skillable labs - could be related to the cloudslice??

**Comment by GraemeMalcolm** [comment]
Non-repro here I'm afraid.
The error indicates that the Microsoft.Sql resource provider isn't registered - the script does that but sometimes it times out. I was under the impression that Skillable has pre-registered all the required providers in the cloud slice subscriptions but I'll follow up and check.
All I can advise for now is to delete the resource group and try re-running the script.

**Comment by Derekp20** [comment]
Thanks Graeme. We have been rerunning scripts, it seems to be in a number of labs. So may well be a Skillable issue.

**Comment by ZekeStarr** [comment]
We've updated the labs so that a script is executed on lab launch that attempts to pre-register the main Resource Providers. Currently, we're targeting: "Microsoft.Synapse", "Microsoft.Sql", "Microsoft.Storage" & "Microsoft.Compute"

I'd call this a band aid for now, but we'll work on it more today to ensure all necessary providers are pre-registered at lab launch.

This will not affect any ongoing lab instances, just new launches.

**Comment by Derekp20** [comment]
The next class session is nextMonday, but I'll check before then. Thanks

**Comment by GraemeMalcolm** [comment]
Thanks @ZekeStarr.
I'll leave this open for now and check back next week to ensure it's fully resolved.

**Comment by TheJamesHerring** [comment]
@ZekeStarr @GraemeMalcolm, I haven't seen anything new open up on the registration of service providers but am confirming. Will close today if nothing crops up from this week.
