### ISSUE TITLE
Json and Parquet sample data files missing

### ISSUE THREAD

**Issue by TirendraR** [MicrosoftLearning/dp-203-azure-data-engineer#64]
Hi,

I am working through the Microsoft Learn Data engineering path and in the lesson.

**Lesson**
[Learn Module Lesson](https://learn.microsoft.com/en-us/training/modules/query-data-lake-using-azure-synapse-serverless-sql-pools/5-exercise-sql)

The sample files for the sales data in Parquet and Json seem to missing from LAB01 as mentioned in the instructions.

**Path to lab instructions**
[Lab Instructions](https://microsoftlearning.github.io/DP-500-Azure-Data-Analyst/Instructions/labs/01-analyze-data-with-sql.html)

Can you please assist in adding the files to the labs? 

Thank you,
Kind regards
Tirendra

**Comment by GraemeMalcolm** [comment]
Did you clone the repo and run the setup script for the appropriate lab? If so, can you share the output generated by the script?

**Comment by TirendraR** [comment]
I seem to have cloned the wrong repo. I will check in the other one :) 

Appologies. and thank you.
