### ISSUE TITLE
Lab 18 Exercise Ingest streaming data into Azure Synapse Analytics - Module Not Found

### ISSUE THREAD

**Issue by virajvaidya** [MicrosoftLearning/dp-203-azure-data-engineer#66]
Module: Ingest realtime data with Azure Stream Analytics and Azure Synapse Analytics
 Lab/Demo: 18
 Task: Ingest streaming data into a dedicated SQL pool
 Step: 06

Description of issue

The following command ( run a client app that sends 100 simulated orders to Azure Event Hubs) doesn't work:

 node ~/dp-203/Allfiles/labs/18/orderclient

When running the above in PowerShell, the following error is thrown:

Error: Cannot find module '/home/name/dp-203/Allfiles/labs/18/orderclient'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

Thanks for your help with this.

**Comment by GraemeMalcolm** [comment]
Make sure you've successfully run ./setup.ps1 in the dp-203/Allfiles/labs/18 folder as instructed in the earlier steps - this is what creates the orderclient.js module. If you've done that, this is what you should see:
<img width="827" alt="orderclient" src="https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/11771134/a5f8521c-6233-4160-ba59-badcc587e12c">
