### ISSUE TITLE
Lab 22 Synapase-purview

### ISSUE THREAD

**Issue by NFGodoy** [MicrosoftLearning/dp-203-azure-data-engineer#67]
# Module: 08
#### Step: 00

Description of issue

Repro steps:

1. Only one student could create the purview account
2. The others got an error because one purview account was already created for the tenant. It looks like the rules have changed since the last time I run the course, because we could create multiple accounts in the same tenant, one per azure subscription. Now we can't. 
3. As the instructor I have tried the lab and it worked fine. I couldn't reproduce the issue as I was probably the first one creating the account at the time I tried the lab later in the day after the "disaster" during the class. My students were very upset as Purview was a subject  that most of them were very keen to experiment with.

**Comment by GraemeMalcolm** [comment]
This is a known issue after an update to the Purview service. See the following note at the beginning of the exercise:

Important: Microsoft Purview has been updated to restrict the number of Microsoft Purview accounts available per Azure tenant. Consequently, this lab is not supported in shared tenant environments, including many hosted lab environments used in instructor-led training courses.
