### ISSUE TITLE
Databricks: Data renamed to Catalog

### ISSUE THREAD

**Issue by athelen20** [MicrosoftLearning/dp-203-azure-data-engineer#68]
# Module: 00
#### Step: 05

Description of issue
"Data" task was renamed to "Catalog"
Old: 
![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/60407620/08b9f51e-63dc-4d57-8eac-cf18e5b4ca55)

New: ![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/60407620/f6e038f1-adfe-42eb-9414-f2ea540ba768)

Repro steps:
Old: In the tab on the left, select the Data task, and verify that the products table ....
New: In the tab on the left, select the Catalog task, and verify that the products table h

**Comment by GraemeMalcolm** [comment]
Thanks @athelen20 - resolved
