### ISSUE TITLE
Modify setup to not require admin permissions

### ISSUE THREAD

**Issue by TeamDman** [MicrosoftLearning/dp-203-azure-data-engineer#69]
# Module: dp-203
## Lab/Demo: all

Description of issue

The setup scripts ([example](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/blob/master/Allfiles/labs/01/setup.ps1)) require admin permissions to

1. register resource providers
2. create resource groups

My org does not give these permissions our cloud users. We have mechanisms in place for users to request that resource providers be enabled, and for resource groups to be created, but they never receive the permissions to do so themselves.

I propose that the setup scripts are modified to:

1. fail with a clear error message if a require resource provider is not registered when the user doesn't have the ability to register it 
2. prompt the user to let them use an existing resource group instead of requiring the creation of a new one

additionally, it looks like the script checks azure regions for compatibility with services, but the [list of preferred regions](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/blob/master/Allfiles/labs/01/setup.ps1#L87C1-L87C32) doesn't include `canadacentral`.
Perhaps this could also be a user prompt, and if the user-entered region fails the check only then would it attempt to automatically find a compatible one for them?

**Comment by TheJamesHerring** [comment]
These labs are for ILT content providers. If the provider isn't properly registered, the lab user will be unlikely to complete the lab outside of the controlled environment.
