### ISSUE TITLE
Improper Star Scema Representation

### ISSUE THREAD

**Issue by Jason-Microsoft-MTT** [MicrosoftLearning/dp-203-azure-data-engineer#7]
# Module: 2
#### Step: 5 and 6

Description of issue
the way the instructions have it, the relationship is filtering from the fact table (SalesOrder) to the Dim tables (Product, Customer) which isnt a correctly formatted model

the relationships for the SalesOrder table should be created in the To section which properly represents how models should filter rom Dim to Fact tables (image included)
<img width="762" alt="Screenshot 2023-02-28 090648" src="https://user-images.githubusercontent.com/120508481/221894037-574b4a64-c2a5-4bad-9101-251555a9c426.png">

Repro steps:

1.
1.
1.

**Comment by GraemeMalcolm** [comment]
Lab updated to reverse relationship direction
