### ISSUE TITLE
Add more instructions for users to paste the folder path rather than browsing

### ISSUE THREAD

**Issue by dtarek1** [MicrosoftLearning/dp-203-azure-data-engineer#72]
# Module: 01
#### Step: 08

Description of issue
In this step, users always opt for browsing for the file instead of pasting it in the text box. This folder doesn't exist and will be created, so they always end up browsing and not finding the file. I faced this with multiple users over many deliveries. 

It would be good to add in the instructions that they should paste this in the box and not browse, to make it clearer for them.

Repro steps:

After selecting the connection, on the Destination/Dataset step, ensure the following settings are selected, and then select Next >:
Folder path: files/product_data
1.
1.
1.

**Comment by rublaman** [comment]
I had to create the folder manually in the storage...
