### ISSUE TITLE
There is not product_data folder in the Module 01 - Explore Azure Synapse Analytics

### ISSUE THREAD

**Issue by rublaman** [MicrosoftLearning/dp-203-azure-data-engineer#73]
# Module: 01
#### Step: 08

Description of issue

There is not any folder called `product_data` when the tutorial says "Folder path: files/product_data". 

I had to create the folder manually in the storage account inside the files folder.

Repro steps:

1.
1.
1.

**Comment by GraemeMalcolm** [comment]
The instructions explicitly say to specify **files/product_data** in the destination folder path
