### ISSUE TITLE
Lab 11

### ISSUE THREAD

**Issue by athelen20** [MicrosoftLearning/dp-203-azure-data-engineer#74]
# Module: 00
#### Step: 8

Description of issue
Several students report that the instructions are not well given AND that the notebook was not pre-loaded into their environment (by the script?)

**Comment by Mihai-Ac** [comment]
Hello @athelen20 

I just ran the setup file (following the instructions) and the **Spark Transform** notebook was loaded
![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/110993710/ce2e069c-39dc-4ba2-9c42-c0d2191d2907).
With regards to the notebook not showing, confirm that the students have administrative level access on the subscription and that there were no errors during the setup.

Regarding the part with the instructions not well given, can you please give some examples?

**Comment by Sp3ci3s8472** [comment]
I opened a duplicate ticket, sorry. This is #77 
I did run into errors during the setup, which I listed at that issue. 

This is my personal account where I have administrative level access on my subscription and all previous labs (DP900 and DP203) ran perfectly.

**Comment by GraemeMalcolm** [comment]
Closing as duplicate
