### ISSUE TITLE
Wrong container name

### ISSUE THREAD

**Issue by adams00** [MicrosoftLearning/dp-203-azure-data-engineer#78]
# Module: 00
#### Step: 9

Description of issue
In: 
https://microsoftlearning.github.io/dp-203-azure-data-engineer/Instructions/Labs/14-Synapselink-cosmos.html#query-azure-cosmos-db-from-azure-synapse-analytics

Name of the cosmosDB container is "Sales". Schould be "sales'.
Shows error while querying table "salesorders"

**Comment by GraemeMalcolm** [comment]
The instruction in the **Create an analytical store container** section is to create a container named Sales.
