### ISSUE TITLE
Azure CloudShell old versions of node and npm

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/dp-203-azure-data-engineer#79]
# Module: 6
#### Step: 00

Description of issue
Older depricated versions of npm and node in Azure Cloudshell

Repro steps:
After the setup, the node client to produce events gives this warning.
![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/10166617/3d978ac7-e2d9-462b-b532-30b7930b8cc6)

if you check the npm and node versions of the cloudshell you see older depricated versions:
![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/10166617/820e96aa-0c8d-479e-a85d-5e7fc98fce85)

With the package.json configured
"dependencies": {    "@azure/event-hubs": "^5.11.3"  }
the client still works for now, but some day it will not anymore.

You cannot upgrade Azure Cloud Shell yourself. 

To use the latest version @azure/core-amqp and @azure/event-hubs you need to have node 18 installed.

1.
1.
1.

**Comment by Jason-Microsoft-MTT** [comment]
Just echoeing this issue

**Comment by GraemeMalcolm** [comment]
Thanks. I pinned the previous version of the EventHubs npm package, which resolves the issue for now We'll explore updating the latest version when the default node installation in the cloud shell catches up.

**Comment by Jason-Microsoft-MTT** [comment]
[celebrate]     Jason Richards reacted to your message:
________________________________
