### ISSUE TITLE
Data Explorer pool not being created in Synapse Analytics lab

### ISSUE THREAD

**Issue by rtb144** [MicrosoftLearning/dp-203-azure-data-engineer#83]
# Module: 
#### Step: 08

Description of issue

The guide shows the following:
"Apache Spark pools:
sparkxxxxxxx: that you can use on-demand to explore or process data in a data lake by using programming languages like Scala or Python. <!— - Data Explorer pools:
adxxxxxxxx: A Data Explorer pool that you can use to analyze data by using Kusto Query Language (KQL). —>"

Unfortunately, there is no "adxxxxxxxxx" created.  

Also, the Data Explorer pools is not formatted correctly in the documentation as a subheader 

Repro steps:

1. open PS command line in Azure 
2. run 'git clone https://github.com/MicrosoftLearning/dp-203-azure-data-engineer dp-203'
3. cd dp-203/Allfiles/labs/01
4. run './setup.ps1'
5. validate in Synapse Analytics Studio

**Comment by TheJamesHerring** [comment]
Can you verify the lab and Step number: Here's where I'm looking and I see nothing about ADX:


![Bug](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/49248205/a2523d13-efcd-4d58-af1a-93cfdd656d89)

**Comment by GraemeMalcolm** [comment]
@TheJamesHerring , it shows up in the lab steps at https://microsoftlearning.github.io/dp-203-azure-data-engineer/Instructions/Labs/01-Explore-Azure-Synapse.html#explore-synapse-studio.
It looks like it's been commented out using  HTML syntax but still gets rendered. Best solution would be to delete it.

**Comment by TheJamesHerring** [comment]
Thanks for that @GraemeMalcolm, @rtb144 please let me know if you have any other issues. Removed the "commented out" code so it's completely gone. JH
