### ISSUE TITLE
Module "Implement a Data Streaming Solution with Azure Stream Analytics" - Cross check lab content

### ISSUE THREAD

**Issue by k-krupka** [MicrosoftLearning/dp-203-azure-data-engineer#86]
# Module: Get started with Azure Stream Analytics 
#### Step: 5

[ ./setup.ps1](https://microsoftlearning.github.io/dp-203-azure-data-engineer/Instructions/Labs/17-stream-analytics.html)

Description of issue

Hi team, 
Nothing broken, low importance. After running the command:
```
 ./setup.ps1
```
I've got the following message:
![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/20299573/4ffdc1ec-2443-4dbd-a178-b56bdacbd9d6)

Dunno if we wanna take any action, but we might want to double check for backwards compatibility, so that the lab is not broken. 

The rest of the lab looks good :)

**Comment by TheJamesHerring** [comment]
Thanks, will keep an eye on this as this will require a potential change with the underlying VM. Will leave it open until we meet this week (Wednesday to discuss the roadmap).
