### ISSUE TITLE
Lab 4 - AD is now Entra + typo

### ISSUE THREAD

**Issue by douwevandenberg** [MicrosoftLearning/dp-203-azure-data-engineer#87]
# Module: 02
## Lab/Demo: 04

Some minor issues.

Lab: Analyze data in a lake database
Section: Modify container permissions
Step 2 has a typo: "Select the Storage account for you data lake named datalakexxxxxxx" <--you should be your

More important, step 4 refers to "Access key (Switch to Azure AD User Account) click on this to change to Azure AD User Account." 
This is now "Authentication method: Access key (Switch to Microsoft Entra user account)"

**Comment by TheJamesHerring** [comment]
Thanks for the note.
JH
