### ISSUE TITLE
DBC upload error generated but file loaded

### ISSUE THREAD

**Issue by Jason-Microsoft-MTT** [MicrosoftLearning/dp-203-azure-data-engineer#9]
# Module: 09
#### Step: 02

Description of issue
When the learner submits the url request, there is an error generated (image included). The file does seem to import though, as there were several instances of the same file. Not sure why the error is produced.

<img width="554" alt="Screenshot 2023-03-02 152757" src="https://user-images.githubusercontent.com/120508481/222560324-2bc83388-915f-402e-b3f0-0ccb08fb783b.png">

<img width="287" alt="Screenshot 2023-03-02 152842" src="https://user-images.githubusercontent.com/120508481/222560385-180ffc69-5fae-4f22-b53a-e8df1bfb16e5.png">

Repro steps:

1.
1.
1.

**Comment by Jason-Microsoft-MTT** [comment]
I did go to this site and downloaded the DBC straight from Github into their local VM and uploaded it without any generated errors as an FYI.

**Comment by GraemeMalcolm** [comment]
Is this happening for multiple learners, or is it an isolated case?

**Comment by Jason-Microsoft-MTT** [comment]
Im unsure as the students are all in different phases of labs or they aren't communicating it.

**Comment by GraemeMalcolm** [comment]
Can you repro it?

**Comment by Jason-Microsoft-MTT** [comment]
Im opening up a lab now to try.

**Comment by GraemeMalcolm** [comment]
I get the same error - investigating now...

**Comment by Jason-Microsoft-MTT** [comment]
I did as well and its not limited to that specific file...any upload from a url I attempt generates the same error, but does import the notebook, so its not the file.

**Comment by GraemeMalcolm** [comment]
It works for importing .ipynb notebooks, just not .dbc. 
We might switch to that format anyway because it's easier to localize.

**Comment by Jason-Microsoft-MTT** [comment]
odd since importing from a local file didnt cause the error. I did see something about network issues causing that problem, but it wasnt related to databricks. Either way, at least learners won't think something's off.

**Comment by GraemeMalcolm** [comment]
OK, I updated all of the notebooks to ipynb format and updated the instructions. That seems to resolve the issue - whatever it is!
