### ISSUE TITLE
Lab 6 - storage blob data owner not always set

### ISSUE THREAD

**Issue by douwevandenberg** [MicrosoftLearning/dp-203-azure-data-engineer#90]
# Module: 3
#### Step: 00

Description of issue
Half of my class did not have storage blob data owner rights on the data lake, causing the spark notebook to fail. I'm assuming there's an issue with async processes?

Repro steps:

1. roll out the environment for the 'Transform Data in a data lake with Spark' lab
1. Import the notebook
1. Try to run the notebook

**Comment by TheJamesHerring** [comment]
I will follow-up. I didn't run into issue but have email with hosting vendor.
JH

**Comment by douwevandenberg** [comment]
I ran the course again last week. The issues weren't as widespread, but about 1 in 10 now had the issue of no rights on the data lake.

**Comment by TheJamesHerring** [comment]
@douwevandenberg thank you for the update. It's in the queue and will follow-up if we find anything definitive on the issue. If it happens again, can you get screenshots and share them, they do provide some value and if through hosting provider for the lab, please have students open a ticket as these are currently in a maintenance period and only changes to the underlying architectures should break these labs. Thanks again! JH

**Comment by TheJamesHerring** [comment]
Closing issue as we're unable to repeat this issue per my own and additional testing. Notes are to open ticket with lab hosting provider and provide screenshots if it persists. Thanks for input, keep it up! JH
