### ISSUE TITLE
Edge very outdated in ALH labs. Edge crashes during setup fase.

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/dp-203-azure-data-engineer#91]
# Module: 00
#### Step: 00

Description of issue
Everytime a lab is started at ALH (Skillable), Edge is so old that it forces to be update. So during the labs setup, Edge crashes. So the resource group is deployed, but the post configuration is skipped. Very annoying and time consuming.

Please update the images of the vms. 

Repro steps:
Just start any lab. 
1.
1.
1.

**Comment by GraemeMalcolm** [comment]
@TheJamesHerring, could we get Skillable to refresh the VM image used across DP-203 (install latest updates and go through the "first-time use" with Edge)?

**Comment by TheJamesHerring** [comment]
@GraemeMalcolm et al., I've put in a request to Skillable to get the images updated. I'll keep you posted as they're very responsive.  JH

**Comment by tylerfarmer1** [comment]
I can confirm I'm having the same issue in my class.  After the script completes, you click on the "All Resources" button in the Azure portal, and Edge just closes.

**Comment by TheJamesHerring** [comment]
Update: Still waiting for an update on Edge within labs. Will have them tested after the base image is updated and close this.
JH

**Comment by TheJamesHerring** [comment]
An update: this is being worked on, it may take a few cycles as there are many labs across several courses that are impacted.
Best, JH

**Comment by TheJamesHerring** [comment]
Closing as this issue will take some time from a vendor, but is being updated.
