### ISSUE TITLE
Lab 04 - Analyze data in a lake database, Spark session won't Insert new rows

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/dp-203-azure-data-engineer#92]
# Lab 04: Analyze Data in a Lake Database
#### Step: 3

Description of issue:

Step 3 is to insert a new row of data into the SalesOrder table.   It seems to always fail, and it appears to be a permissions issue.  I have tested in my 'regular' Azure subscription as well as using the lab hoster, and all my students this week had the issue.   

I made sure we did the instructions at the top of the lab where you "Modify Container Permissions" but it seems to fail whether you make that change or not.

**Comment by caeltheloved** [comment]
Hi Tyler, I had the same issue as well. Quick question . What is the folder path in Azure Data Lake Storage you created your table from? In my first attempt I used a different folder path and it caused some issues. 

Can you verify that your file path in ADLS is files/RetailDB/SalesOrder ?

PS/NB: I'm not a an official Microsoft spokesperson, just someone taking the course and seeing an opportunity to be of help.

**Comment by TheJamesHerring** [comment]
Having tester check.

**Comment by caeltheloved** [comment]
Thank you.

**Comment by TheJamesHerring** [comment]
To add to @afelix-95 's question and confirm. These are being run through a hosted lab environment, correct? If so, I would also ask that as a general practice that you open a ticket with the hosting provider through the lab and then we can follow-up on our end as well.

**Comment by TheJamesHerring** [comment]
Unable to repeat in any environment and cross regions. Guidance is to open ticket with lab hosting provider and if the problem persists or reappears, please also take screenshots to assist in understanding. Please continue to contribute to increasing content quality! JH

**Comment by tylerfarmer1** [comment]
OK thanks, I will re-test when I get a chance and re-open with screen shots if I run into any issues.

Tyler Farmer
***@***.******@***.***>
602-326-1042
