### ISSUE TITLE
dp-500 repo closed - demo links not working

### ISSUE THREAD

**Issue by douwevandenberg** [MicrosoftLearning/dp-203-azure-data-engineer#96]
This course has a dependency on some labs from DP-500. That course has been retired and the links to those labs aren't working anymore. The instructions still exist but the repo states it will not be monitored nor updated. 

Example: the first demo points to https://microsoftlearning.github.io/DP-500-Azure-Data-Analyst/Instructions/labs/01-analyze-data-with-sql.html

This is an issue because we use some of the demos as labs (and our lab hoster actually marks them as labs). For now there is no urgent issue, the instructions still exist in the repo our lab hoster uses and can also be found by going to the original github.com repo of dp-500. However, I would suggest this course takes over maintenance of those demos.

**Comment by TheJamesHerring** [comment]
This should be resolved. Thanks for the notification.
