### ISSUE TITLE
Lab 08: Intermittent error/issue at end of setup.ps1

### ISSUE THREAD

**Issue by SkillableKarl** [MicrosoftLearning/dp-203-azure-data-engineer#98]
# Module: 00
#### Step: 05

Description of issue

Intermittently, the following error is received at the end of the setup.ps1 script:
![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/65239900/d58f6588-2918-491d-b80d-6e0cd19ce1db)

Repro steps:

1. Take lab, as-written

Troubleshooting:

In checking, it looks like az.synapse was updated quite recently to v3.0.8:  https://www.powershellgallery.com/packages/Az.Synapse/3.0.8 
![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/65239900/acc7db86-510f-472d-8364-f828dbb0c022)

This error does not appear in every launch, and may well be intermittent due to various regions from which it is launched not installing the very latest version.....YET.  See also previously filed issue that is likely same issue: https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/issues/97

If I download the files *but* first edit the setup.ps1 to alter the cmd that installs the az.synapse before running it from:

Install-Module -Name Az.Synapse

to

Install-Module -Name Az.Synapse -RequiredVersion 3.0.7 

...it does seem to complete successfully:
![image](https://github.com/MicrosoftLearning/dp-203-azure-data-engineer/assets/65239900/a2b66320-c301-4e51-8077-58246e3df18e)

**Comment by TheJamesHerring** [comment]
Keeping an eye on this and will add it to tasks. I will also have tester go through this asap.
JH

**Comment by TheJamesHerring** [comment]
Closing as not seen or reported post Build. Suspect it was intermittent from updates but will keep my eyes open.
JH

**Comment by SkillableKarl** [comment]
Ive tested a launch in various DCs, both ALH & Azure and have _not_ been able to reproduce it this morning!
