### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by BI-crypto** [MicrosoftLearning/dp-203-azure-data-engineer#99]
# Module: Delta Lake Tables
#### Step: Before you start - 5

Description of issue
cannot install the module
Repro steps:

1.   rm -r dp-203 -f
 git clone https://github.com/MicrosoftLearning/dp-203-azure-data-engineer dp-203
2. cd dp-203/Allfiles/labs/07
 ./setup.ps1

**Comment by TheJamesHerring** [comment]
had tested and ran my own tests with no problems. Please share screenshot and/or error messages received from lab environment.
 
PS C:\learn-pr\mslearn-fabric> git clone https://github.com/MicrosoftLearning/dp-203-azure-data-engineer dp-203
Cloning into 'dp-203'...
remote: Enumerating objects: 1411, done.
remote: Counting objects: 100% (84/84), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 1411 (delta 42), reused 56 (delta 27), pack-reused 1327
Receiving objects: 100% (1411/1411), 28.69 MiB | 27.77 MiB/s, done.
Resolving deltas: 100% (738/738), done.
Updating files: 100% (319/319), done.
PS C:\learn-pr\mslearn-fabric> cd dp-203/Allfiles/labs/07
PS C:\learn-pr\mslearn-fabric\dp-203\Allfiles\labs\07> ./setup.ps1

Closing as no issues seen.
